apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
       feature: exec
  template:
    metadata:
       labels:
         feature: exec
    spec:
      containers:
      - name: agnhost
        image: registry.ddbuild.io/e2e-test-images/agnhost:2.32
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: nodeless
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/nodeless
                operator: Exists
